# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"+\n\rProductVector\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06vector\x18\x02 \x03(\x01\"\x18\n\x06Vector\x12\x0e\n\x06vector\x18\x01 \x03(\x01\x42\x0cZ\n./genprotob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./genproto'
  _PRODUCTVECTOR._serialized_start=17
  _PRODUCTVECTOR._serialized_end=60
  _VECTOR._serialized_start=62
  _VECTOR._serialized_end=86
# @@protoc_insertion_point(module_scope)
